---
title: "Publications"
---

View at [Google Scholar profile](https://scholar.google.com/citations?user=CdVwjyUAAAAJ&hl=en&oi=sra)


## Journal articles

### Submitted

Rovellini, A., A.E. Punt, M.W. Dorn, I.C. Kaplan, M.D. Bryan, G. Adams, K. Aydin, M.R. Baker, C.L. Barnes, B.E. Ferriss, E.A. Fulton, M.A. Haltuch, A.J. Hermann, K.K. Holsman, C. McGilliard, E.A. McHuron, **H. Morzaria-Luna**, S. Surma. Evaluating ecosystem caps on fishery yield in the context of climate stress and predation. Fish and Fisheries.

Schamp, A., **H. Morzaria-Luna**, C.M. Anderson, M. Knox. Tourist Preferences for Whale Watching and Rule Changes in the Salish Sea. Oceans and Coastal Management. [Preprint at SSRN] (https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4409663)

Arvizu-Ruiz, A., R.H. Barraza-Guardado, A. Riesgo-Ruiz, **H. Morzaria-Luna**, J.M. Dorantes Hernández. Evidence of overfishing of the pink murex snail <i>Phyllonotus erythrostomus</i> in Bahía de Kino, Sonora (Gulf of California). Oceanides


### Published

Salas-Mejia, N. J.G. Padilla-Serrato, **H. Morzaria-Luna**, T.M. Ruiz-Ruiz, E.F. Balart-Paez, J.A. Arreola Lizárraga. Accepted. Spatial-temporal patterns and changes in the structure of the fish community in a semi-arid subtropical coastal lagoon subject to ecological conservation. Regional Studies in Marine Science.

Ortega-Cisneros, K. D. Fierros-Arcos, M. Lindmark, C. Novaglio, P. Woodworth-Jeffcoats, T.D. Eddy, M. Coll, E. Fulton, R. Oliveros-Ramos, J. Reum, Y. Shin, C. Bulman, L. Capitani, S. Datta, K. Murphy,  A. Rogers, L. Shannon, A. Whitehouse, Y. Lun Wu, E. Adekoya, C. Barceló, B.S. Dias, A. Fuster, C. Hansen, B. Husson, V. McGregor, A. Morell, **H. Morzaria Luna**, 
J. Ouled-Cheikh Bonan, J. Ruzicka, J. Steenbeek, I. Stollberg, R.C. Subramaniamoshni, M. Travers- Trolet, V. Tulloch, A. Bryndum-Buchholz, C. Harrison, R. Heneghan, O. Maury, C. M. Petrik, K. Roberts, D.P. Tittensor, J. Blanchard.
Accepted. An Integrated Global-to-Regional Scale Workflow for Simulating Climate Change Impacts on Marine Ecosystems. Earths Future

Beaty, F., P. S. Domínguez-Sánchez, K. Bear Nalven, J. Palacios-Abrantes, KL. Oken, N.C. Ban, K.J. Nickols, F. Juanes, T.A. Okey, A. Spalding, H. Morzaria-Luna, L.D. Jenkins, V. Tulloch, I. McKechnie. 2024. [Centering relationships to place for more meaningful research and engagement.](https://www.pnas.org/doi/10.1073/pnas.2306991121)
Proceedings of the National Academy of Sciences. 121 (25) e2306991121

Rovellini, A., Punt, André E., Bryan, Meaghan D., Kaplan, I., Dorn, M., Aydin, K., Fulton, E.A., Alglave, B., Baker, M.R., Carroll, G., Ferriss, B., Haltuch, M.A., Hayes, A., Hermann, A., Hernvann, P.Y., Holsman, K. Liu, O.R., McHuron, E., **Morzaria-Luna, H.**, Moss, J., Surma, S. & Weise, M.T. 2024. [Linking climate stressors and ecological processes in ecosystem models, with a case study from the Gulf of Alaska](https://academic.oup.com/icesjms/advance-article/doi/10.1093/icesjms/fsae002/7584994). ICES Journal of Marine Science https://doi.org/10.1093/icesjms/fsae002 

**Morzaria-Luna, H.**, M. Urquidi, G. Cruz-Piñón, J.M. Dorantes Hernández, P.A. Valdivia Jiménez, Á. Sánchez Cruz & I. Martínez. 2023. [Historical use of coastal wetlands by small-scale fisheries in the Northern Gulf of California.](https://rdcu.be/diR8B) Human Ecology. https://doi.org/10.1007/s10745-023-00440-x

Perryman, H.A., I.C. Kaplan, JL. Blanchard, G. Faye, S.K. Gaichas, V.L. McGregor, **H. Morzaria-Luna**, J. Porobic, H. Townsend & E.A. Fulton. 2023. [Atlantis Ecosystem Model Summit 2022: report from a workshop.](https://doi.org/10.1016/j.ecolmodel.2023.110442). Ecological Modeling. https://doi.org/10.1016/j.ecolmodel.2023.110442

Lovindeer, R., S. Mynott, J. Porobic Garate, E.A. Fulton, S.E. Hook, H. Pethybridge, S.E. Allen, D. Latornell, **H. Morzaria-Luna** & J. Melbourne-Thomas. 2023. Ecosystem-level Impacts of Oil Spills: A Review of Available Data with Confidence Metrics for Application to Ecosystem Models. Environmental modeling and assessment. https://doi.org/10.1007/s10666-023-09905-1

Walker, S.L., **H. Morzaria-Luna**, I.C. Kaplan & D. Petatán-Ramírez. 2022. Future temperature and salinity in Puget Sound, Washington State, under CMIP6 climate change scenarios. Journal of Water and Climate Change 13(12): 4255–4272. https://doi.org/10.2166/wcc.2022.282

**Morzaria-Luna H** & Zedler JB (2022) Salt marsh restoration surprise: A subordinate species accumulates and shares nitrogen while outcompeting salt marsh dominants. Frontiers in Ecology and Evolution 10:851055. doi: 10.3389/fevo.2022.851055

Calderon-Aguilera, L.E., H. Reyes-Bonilla, **H. Morzaria-Luna**, J.C. Perusquía-Ardón, M. Olán-González, & M.F. Méndez-Martínez. 2022. [Resistance and resilience of marine ecosystems are poorly correlated with local oceanographic conditions and human stressors in the Eastern Pacific](https://authors.elsevier.com/a/1g5jgI7ECuHkJ). Progress in Oceanography. 209:102922. https://doi.org/10.1016/j.pocean.2022.102922

**H. Morzaria-Luna**, C.H. Ainsworth, R.L. Scott. 2022. [Impacts of deep-water spills on mesopelagic communities and implications for the greater pelagic food web](https://www.int-res.com/abstracts/meps/v681/p37-51/). Marine Ecology Progress Series. 681: 37--51. https://doi.org/10.3354/meps13900

Salvadeo, C., **H. Morzaria-Luna**, H. Reyes-Bonilla, A. Ivanova-Bonchera, D. Petatán Ramírez, E. Juárez-León. 2021. Fisher's perceptions inform adaptation measures to reduce vulnerability to climate change in a Mexican Natural Protected Area. Marine Policy. 134: 104793. https://doi.org/10.1016/j.marpol.2021.104793

**Morzaria-Luna, H.**, P. Turk-Boyer, J.M. Dorantes-Hernández, E. Polanco-Mizquez, C. Downton-Hoffmann, G. Cruz-Piñón, T. Carrillo-Lammens, R. Loaiza-Villanueva, P. Valdivia-Jiménez, Á. Sánchez-Cruz, V. Peña-Mendoza, A. Montserrat López-Ortiz, V. Koch, L. Vázquez-Vera, J. Alfredo Arreola-Lizárraga, I. G. Amador-Castro, A.N. Suárez Castillo & A. Munguia-Vega. 2020. MethodsX. 7: 101108. https://doi.org/10.1016/j.mex.2020.101108.

**Morzaria-Luna, H.**, P. Turk-Boyer, E. Polanco-Mizquez, C. Downton-Hoffmann, G. Cruz-Piñón, T. Carrillo-Lammens, R. Loaiza-Villanueva, P. Valdivia-Jiménez, Á. Sánchez-Cruz, V. Peña-Mendoza, A. Montserrat López-Ortiz, V. Koch, L. Vázquez-Vera, J., Arreola-Lizárraga, A., I. G. Amador-Castro, A.N. Suárez Castillo & A. Munguia-Vega. 2020. Coastal and Marine Spatial Planning in the Northern Gulf of California, Mexico: Consolidating Stewardship, Property Rights, and Enforcement for Ecosystem-Based Fisheries Management. Ocean and Coastal Management. 197:105316. https://doi.org/10.1016/j.ocecoaman.2020.105316

Kaplan IC, Hansen C, **Morzaria-Luna H**, Girardin R and Marshall KN. 2020 Ecosystem-Based Harvest Control Rules for Norwegian and US Ecosystems. Front. Mar. Sci. 7:652. doi: 10.3389/fmars.2020.00652

Gruss, A., Thorson, J., Carroll, G., Ng, E., Holsman, K., Aydin, K., Kotwicki, S., **Morzaria-Luna, H.**, Ainsworth, C., and Thompson, K. 2020. Spatio-temporal analyses of marine predator diets from data-rich and data-limited systems. Fish and Fisheries. https://doi.org/10.1111/faf.12457

Petatán-Ramírez, D., M.Á. Ojeda-Ruiz, L. Sánchez-Velasco, C. Salvadeo, D. Rivas, H. Reyes-Bonilla, G. Cruz-Piñón, **H. Morzaria-Luna**, A.M. Cisneros-Montemayor and W. Cheung. 2019. Potential changes in the distribution of suitable habitat for Pacific sardine (Sardinops sagax) under climate change scenarios. Deep Sea Research Part II. Topical Studies in Oceanography. https://doi.org/10.1016/j.dsr2.2019.07.020

Stranges, S, AP Cuervo-Robayo, E Martínez-Meyer, **H. Morzaria-Luna**, and H Reyes-Bonilla. 2019. Potential changes in the distribution of the genus Pocillopora (Anthozoa: Scleractinia) in the Eastern Tropical Pacific under climate change scenarios. Revista Mexicana de Biodiversidad 90: e902696. doi: 10.22201/ib.20078706e.2019.90.2696

**Morzaria-Luna, H**, Ainsworth, CH, Tarnecki, JH and Grüss, A, 2018. Diet composition uncertainty determines impacts on fisheries following an oil spill. Ecosystem Services. https://doi.org/10.1016/j.ecoser.2018.05.002

Olsen E, Kaplan IC, Ainsworth C, Fay G, Gaichas S, Gamble R, Girardin R, Eide CH, Ihde TF, **Morzaria-Luna H**, Johnson KF. 2018. Ocean Futures under ocean acidification, marine protection, and changing fishing pressures explored using a worldwide suite of ecosystem models. Frontiers in Marine Science 1:5-64. https://doi.org/10.3389/fmars.2018.00064

Álvarez‐Romero JG, Munguía‐Vega A, Beger MM, Mancha‐Cisneros M, Suárez‐Castillo AN, Gurney GG, Pressey RL, Gerber LR, **Morzaria‐Luna H**, Reyes‐Bonilla H and Adams VM. (2018). Designing connected marine reserves in the face of global warming. Global change biology, 24, pp.e671-e691. doi: 10.1111/gcb.13989.

**Morzaria-Luna, H**, Cruz-Piñón, G, Brusca, RC, López-Ortiz, AM, Moreno-Báez, M, Reyes-Bonilla, H, & Turk-Boyer, P. 2018. Biodiversity hotspots are not congruent with conservation areas in the Gulf of California. Biodiversity and Conservation, 1-24. https://doi.org/10.1007/s10531-018-1631-x

Munguia-Vega, A., A.L. Green, O. Aburto-Oropeza, A.M. Cisneros-Montemayor, G. Cruz-Piñón, G. Danemann, M.J. Espinosa-Romero, A. Giron-Nava, O. Gonzalez-Cuellar, C. Lasch, M. del M. Mancha-Cisneros, S.G. Marinone, M. Moreno-Baez, **H. Morzaria-Luna**, H. Reyes-Bonilla, A.N. Suarez-Castillo, J. Torre, P. Turk-Boyer, M. Walther & A. Hudson Weaver. 2018. Ecological guidelines for designing a network of marine reserves in the unique biophysical environment of the Gulf of California. Ecological Applications 28:749. https://doi.org/10.1007/s11160-018-9529-y

Munguía-Vega, A., J. Torre, P. Turk-Boyer, S. G. Marinone, M. F. Lavín, T. Pfister, W. Shaw, G. Danemann, P. Raimondi, A. Castillo-López, A. Cinti, J. N. Duberstein, M. Moreno-Báez, M. Rojo, G. Soria, L. Sánchez-Velasco, **H.N. Morzaria-Luna**, L. Bourillón, K. Rowell, and R. Cudney-Bueno. 2015. PANGAS: An Interdisciplinary Ecosystem-Based Research Framework for Small-Scale Fisheries in the Northern Gulf of California. Journal of the Southwest 57:337--390. DOI: 10.1353/jsw.2015.0003

**Morzaria-Luna, H.**, P. Turk-Boyer, A. Rosemartin, and V. F. Camacho-Ibar. 2014. Vulnerability to climate change of hypersaline salt marshes in the Northern Gulf of California. Ocean & Coastal Management 93:37--50.

**Morzaria-Luna, H.**, A. Castillo-López, G. H. Danemann, and P. J. Turk Boyer. 2014. Conservation strategies for coastal wetlands in the Gulf of California, Mexico. Wetlands Ecology and Management 22:267--288.

**Morzaria-Luna, H. N.**, P. Turk-Boyer, and M. Moreno-Baez. 2014. Social indicators of vulnerability for fishing communities in the Northern Gulf of California, Mexico: Implications for climate change. Marine Policy 45:182--193.

**Morzaria-Luna, H. N.**, and J. B. Zedler. 2014. Competitive Interactions Between Two Salt Marsh Halophytes Across Stress Gradients. Wetlands:1--12.

**Morzaria-Luna, H.**, C. H. Ainsworth, I. C. Kaplan, P. S. Levin, and E. A. Fulton. 2013. Indirect effects of conservation policies on the coupled human-natural ecosystem of the Gulf of California. PLOS ONE 8 (5): e64.

**Morzaria-Luna, H. N.**, C. H. Ainsworth, I. C. Kaplan, P. S. Levin, and E. A. Fulton. 2012. Exploring trade-offs between fisheries and conservation of the vaquita porpoise (*Phocoena sinus*) Using an Atlantis ecosystem model. PLoS ONE 7:e42917.

Ainsworth, C. H., **H. Morzaria-Luna**, I. C. Kaplan, P. S. Levin, E. A. Fulton, R. Cudney-Bueno, P. Turk-Boyer, J. Torre, G. D. Danemann, and T. Pfister. 2012. Effective ecosystem-based management must encourage regulatory compliance: A Gulf of California case study. Marine Policy 36:1275--1283.

Ainsworth, C. H., **H. Morzaria-Luna**, I. C. Kaplan, P. S. Levin, and E. A. Fulton. 2012. Full compliance with harvest regulations yields ecological benefits: Northern Gulf of California case study. Journal of Applied Ecology 49:63--72.

Ibarra-Obando, S.E., M. Poumian-Tapia, & **H. Morzaria-Luna**. 2010. Long term effects of tidal exclusion on salt marsh plain species at Estero de Punta Banda, Baja California. Estuaries & Coasts. DOI 10.1007/s12237-009-9253-x Volume 33, Issue 3, pp 753-768

**Morzaria-Luna, H. N.**, and J. B. Zedler. 2007. Does seed availability limit plant establishment during salt marsh restoration? Estuaries and Coasts 30:12--25.

Forshay, K. J., **H. N. Morzaria-Luna**, B. Hale, and K. Predick. 2005. Landowner satisfaction with the wetlands reserve program in Wisconsin. Environmental Management 36:248--257.

**Morzaria-Luna, H.**, J. C. Callaway, G. Sullivan, & J. B. Zedler. 2004. Relationship between topographic heterogeneity and vegetation patterns in a Californian salt marsh. Journal of Vegetation Science 15:523--530.

**Morzaria-Luna, H. N.**, K. S. Schaepe, L. B. Cutforth, & R. L. Veltman. 2004. Implementation of bioretention systems: A Wisconsin case study. Journal of the American Water Resources Association 40:1053--1061.

Zedler, J. B., **H. Morzaria-Luna**, & K. Ward. 2003. The challenge of restoring vegetation on tidal, hypersaline substrates. Plant & Soil 253:259--273.

Siqueiros-Beltrones, D.A. & **H. Morzaria-Luna**. 1999. New records of marine benthic diatom species for the Northwestern Mexican region. Oceánides 14(2):89-95

## Book chapters

Turk Boyer, P.J., P. Valdivia Jiménez, E.I. Polanco Mizquez, **H. Morzaria-Luna**, A. Sánchez Cruz and N. Barajas Acosta. 2022. [Gender principle 3: Validating and utilizing different capacities and knowledge of women and men. Participatory coastal-marine spatial planning in the Puerto Peñasco-Puerto Lobos biological and fisheries corridor, Sonora, Mexico](https://wedocs.unep.org/bitstream/handle/20.500.11822/40115/Gender%20Mainstreaming%20in%20Coastal%20and%20Marine%20Ecosystems%20Management%20%20FINAL%20HR.pdf). Gender Mainstreamingin Coastal and Marine Ecosystems Management Principles, Case Studies and Lessons Learned. Amani A. & A. Hanson (Eds.). United Nations Environment Programme. p 24-39.

Cruz Piñón, G., López-Fuerte F.O. & **Morzaria-Luna H.** 2022. Estado del arte de las investigaciones sobre los manglares en Baja California Sur. Ecología y Conservación en los Mares de México. H. Reyes-Bonilla (Ed.). p 6-14

Reyes Bonilla, H., Auliz Ortiz, D., Cruz- Piñón, G. Domínguez Boza, J., Herrero Perezrul, Ma.D., López Pérez, A. Martínez castillo, V., **Morzaria-Luna, H**. Paz García, D.A., Rodríguez Villalobos, J.C. Aranceta Garza, F. Cruz, P. y Balart E.F. 2022. Los Corales Escleratinios de la Bahia de La Paz. Riosmena Rodriguez, R. López Vivas, J.M., Gomez Gallardo U., A.J., Cruz Piñón, G. y A. Romero Piñera (Eds.). En: La Bahía de La Paz: Biodiversidad, procesos ecológicos y sociales. Universidad Autónoma de Baja California Sur. 275-340.

Turk-Boyer, P. J., **H. Morzaria-Luna**, I. Martínez, C. A. Downton-Hoffman, and A. Munguia-Vega. 2014a. Ecosystem-based Fisheries Management of a Biological Corridor along Northern Sonora Coastline. Pages 155--180 in F. Amezcua and B. Bellgraph, editors. Fisheries Management of Mexican and Central American Estuaries. Springer Verlag.

Turk-Boyer, P. J., H. Peña-Bonilla, **H.N. Morzaria-Luna**, P. Valdivia-Jiménez, H. Tovar-Vázquez, and A. Castillo-López. 2014b. Wetland conservation in Northern Sonora, Mexico: Legal tools and active communities. Pages 181--204 Fisheries Management of Mexican and Central American Estuaries. Springer.

**Morzaria-Luna, H.**, A. Iris-Maldonado, and P. Valdivia-Jiménez. 2010. Physico-chemical characteristics of negative estuaries in the Northern Gulf of California, Mexico. Pages 201--223 in Estuaries : Types, Movement Patterns and Climatical Impacts J. R. Crane and A. E. Solomon, editors.

**H. Morzaria-Luna** & Danemann, G.D. 2008. Humedales. In: Danemann, G.D. & E. Ezcurra (eds.). [Bahía de los Ángeles: recursos naturales y comunidad.](https://iefectividad.conanp.gob.mx/i-efectividad/orden_docs/maira/Península%20de%20BC%20y%20PN/RB%20Zona%20Marina%20Bahía%20de%20los%20Ángeles/1%20Contexto%20y%20planeación/Uso%20de%20la%20tierra%20y%20agua/Bahía_recursos%20naturales%20y%20comunidad.pdf)Línea base 2007. Tercera Parte: Aspectos Bioecológicos. Pronatura Noroeste, A.C. Secretaria del Medio Ambiente y Recursos Naturales. Instituto Nacional de Ecología. San Diego Natural History Museum. 243-290.

**H. Morzaria-Luna** & Barocio-León. 2008. Vegetación Terrestre. En: Danemann, G.D. & y E. Ezcurra (eds.). [Bahia de los Ángeles: recursos naturales y comunidad.](https://iefectividad.conanp.gob.mx/i-efectividad/orden_docs/maira/Península%20de%20BC%20y%20PN/RB%20Zona%20Marina%20Bahía%20de%20los%20Ángeles/1%20Contexto%20y%20planeación/Uso%20de%20la%20tierra%20y%20agua/Bahía_recursos%20naturales%20y%20comunidad.pdf) Línea base 2007. Pronatura Noroeste, A.C. Secretaria del Medio Ambiente y Recursos Naturales. Instituto Nacional de Ecología. San Diego Natural History Museum. 215-242.

### Tech memos and reports

Reyes-Bonilla, H., **H. Morzaria-Luna**, G. Cruz Piñón, D. Petatán Ramírez, L. Vázquez Vera, J. Manuel Dorantes, and D. Bernot. 2023 Consultoría para generar evaluaciones de riesgo socioeconómico y biológico, y recomendaciones de medidas de adaptación al cambio climático, para cuatro pesquerías en proceso FIP. 56 pp.

**H. Morzaria-Luna**, I.C. Kaplan, C.J. Harvey, R. Girardin, E.A. Fulton, P. MacCready, B. Chasco, P. Horne, M. Schmidt. 2022. [Design and Parameterization of a Spatially Explicit Atlantis Ecosystem Model for Puget Sound](https://repository.library.noaa.gov/view/noaa/40463). NOAA Technical Memorandum NMFS-NWFSC-177. Northwest Fisheries Science Center, National Marine Fisheries Service, National Oceanic and Atmospheric Administration.

Reyes-Bonilla, H., **H. Morzaria-Luna**, G. Cruz Piñón, D. Petatán Ramírez, L. Vázquez Vera, J. Manuel Dorantes, and J.F. Torres Origel. 2021. Consultoría para generar evaluaciones de vulnerabilidad de las comunidades costeras y de cambio en la disponibilidad de los recursos pesqueros y acuícolas de la costa de México ME-T1347 (CSD/RND). Banco Interamericano de Desarrollo. 98 pp.

Grupo consultor. 2021. [Cambio climático en México: Recomendaciones de política pública para la adaptación y resilienciadel sector pesquero y acuícola.](https://mexico.edf.org/sites/mexico.edf.org/files/Estudio%20sobre%20Cambio%20Clim%C3%A1tico%20en%20M%C3%A9xico%20low.pdf) EDF. ICPMX, Grupo especial de Trabajo en Cambio climático. 77 pp

Porobic J, Pethybridge H, Melbourne-Thomas J, Mynott S, Fulton EA, Gorton R, Hook S, **Morzaria-Luna H**, Allen S, Ban N, Thomas L, Lovindeer R. 2021. Salish Sea Atlantis Model - Parameterisation, calibration and initial results: Direct and indirect ecosystem responses to oil spills and options for interventions. CSIRO Oceans & Atmosphere, Australia.

Ainsworth, C., M. J. Schirripa, and **H. Morzaria-Luna**. 2015. [An Atlantis ecosystem model for the Gulf of Mexico supporting Integrated Ecosystem Assessment.](https://repository.library.noaa.gov/view/noaa/4875) NOAA. NFMS. SFSC, Miami, FL.

Ainsworth, C., I. C. Kaplan, P. S. Levin, R. Cudney-Bueno, E. A. Fulton, M. Mangel, P. J. Turk Boyer, J. Torre, A. Pares-Sierra, and **H. Morzaria-Luna**. 2011. [Atlantis model development for the Northern Gulf of California](https://www.webapps.nwfsc.noaa.gov/assets/25/1505_08012011_125850_AtlantisModelTM110WebFinal.pdf). 293 pp. NOAA Technical Memorandum NMFS-NWFSC-110, U.S. Department of Commerce. National Oceanic and Atmospheric Administration. National Marine Fisheries Service, Seattle, WA.

**Morzaria-Luna, H.**, A. Iris-Maldonado, and P. Valdivia. 2007a. Reporte final técnico de CEDO Intercultural para el proyecto "Estudio Integral Para la Determinación de Agentes Causales de Alta Mortalidad en los Cultivos del Ostión Japonés, Crassostrea gigas, de las Costas de Sonora." Puerto Peñasco, Sonora.

Lavín, M. F., A.I. Ocampo Torres, M. Figueroa, C. Cabrera, V. M. Godínez Sandoval, R. Cudney Bueno, R. D. Loaiza Villanueva, **H. Morzaria-Luna**, S.A. Pérez Valencia. 2007. PANGAS eulerian observations of currents in San Jorge Bay (Gulf of California), with acoustic profilers; June-August 2006. Informe Técnico 66684. Departamento de Oceanografía Física, CICESE. 47 pp.

Danemann, G. **H. Morzaria Luna**, S. Barocio, H. Batché, B. Casillas, J. Castillo, A. González, y S. Muñoz. 2005. Inventario de los Humedales del Corredor Costero La Asamblea-San Francisquito, Baja California. Technical Report to the U.S. Fish and Wildlife Service. Division of Habitat Conservation. Pronatura Noroeste, Dirección de Conservación en Baja California. Ensenada, Baja California, México. 45 pp.

## Outreach products & other unpublished materials

**Morzaria-Luna, H.**, I. C. Kaplan, and C. H. Ainsworth. 2014. Revisions to the Northern Gulf of California Atlantis ecosystem model.

**Morzaria-Luna, H.** 2011. Atlantis Ecosystem Model: A decision support tool for ecosystem based management. Seattle, WA.

**Morzaria-Luna, H.**, I. C. Kaplan, and C. H. Ainsworth. 2011. Serránidos - tendencias y predicciones en el Golfo Norte de California. Seattle, WA.

Ainsworth, C. H., I. C. Kaplan, P. S. Levin, M. Mangel, and **H. Morzaria-Luna**. 2009. Diet compositions of fish species in the Northern Gulf of California. Seattle, WA.

Hornung, M., **H. Morzaria-Luna**, and R. Veltman. 2002. How to build your raingarden.

**Morzaria-Luna, H.** 2009a. Ficha Informativa de los Humedales de Ramsar: Humedales de Bahía Adair.

**Morzaria-Luna, H.** 2009b. Ficha Informativa de los Humedales de Ramsar: Humedales de Bahía San Jorge.

**Morzaria-Luna, H.** 2005. Determinants of plant species assemblages in the California marsh plain: Implications for restoration of ecosystem function. Ph.D. Thesis

**Morzaria-Luna, H.**, E. I. Polanco-Mizquez, S. López-Alvirde, and S. Reyes-Fiol. 2007b. Caracterización de la vegetación de los esteros de Bahía Adair, Estero Morúa, y La Salina y predios circundantes. ANEXO. Puerto Peñasco, Sonora.

## News articles and mentions

[En perjuicio de la pesca, mares mexicanos se calientan por cambio climático.](https://www.excelsior.com.mx/nacional/en-perjuicio-de-la-pesca-los-mares-mexicanos-se-calientan/1482779)

[Cambio climático, desafío para la pesca y acuacultura.](https://www.eleconomista.com.mx/empresas/Cambio-climatico-desafio-para-la-pesca-y-acuacultura-20220131-0095.html)

[Presentación del estudio Cambio climático en México](https://ms-my.facebook.com/ICPMX1/videos/presentaci%C3%B3n-del-estudio-cambio-clim%C3%A1tico-en-m%C3%A9xico/630040608001485/)
